#include QMK_KEYBOARD_H

extern keymap_config_t keymap_config;

#define _CLMK 0
#define _NUMB 1
#define _SYMB 2
#define _NAVI 3
#define _QWRT 4
#define _SYST 5

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_CLMK] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_ESC,
			 KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, KC_TAB,
			 KC_ENT, LSFT_T(KC_A), LGUI_T(KC_R), LALT_T(KC_S), LCTL_T(KC_T), KC_G, KC_M, RCTL_T(KC_N), RALT_T(KC_E), RGUI_T(KC_I), RSFT_T(KC_O), KC_ENT,
			 MO(_NAVI), KC_Z, KC_X, KC_C, KC_D, KC_V, KC_A, KC_B, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, MO(_NAVI),
			 LT(_NUMB, KC_SPACE), LT(_SYMB, KC_BSPACE), LT(_NAVI, KC_DEL), LT(_NAVI, KC_DEL), LT(_NUMB, KC_SPACE), LT(_SYMB, KC_BSPACE)),
	[_NUMB] = LAYOUT(KC_TRNS, KC_NO, KC_NO, KC_LT, KC_GT, KC_NO, KC_NO, KC_0, KC_PDOT, KC_NO, KC_PSLS, KC_TRNS,
			 KC_TRNS, KC_NO, KC_TILD, KC_LCBR, KC_RCBR, KC_UNDS, KC_COLN, KC_7, KC_8, KC_9, KC_PAST, KC_TRNS,
			 KC_TRNS, KC_NO, KC_GRV, KC_LPRN, KC_RPRN, KC_MINS, KC_SCLN, KC_4, KC_5, KC_6, KC_PMNS, KC_TRNS,
			 KC_TRNS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_TRNS, KC_TRNS, KC_EQL, KC_1, KC_2, KC_3, KC_PPLS, KC_TRNS,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[_SYMB] = LAYOUT(KC_TRNS, KC_NO, KC_NO, KC_LT, KC_GT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_TILD, KC_LCBR, KC_RCBR, KC_UNDS, KC_COLN, KC_AMPR, KC_ASTR, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_GRV, KC_LPRN, KC_RPRN, KC_MINS, KC_SCLN, KC_DLR, KC_PERC, KC_CIRC, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_TRNS, KC_TRNS, KC_EQL, KC_EXLM, KC_AT, KC_HASH, KC_NO, KC_TRNS,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[_NAVI] = LAYOUT(KC_TRNS, TO(5), DF(0), DF(1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_INS, KC_HOME, KC_UP, KC_PGUP, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_END, KC_NO, KC_PGDN, KC_NO, KC_TRNS,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[_QWRT] = LAYOUT(KC_TRNS, KC_1, KC_2, KC_TRNS, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS,
			 KC_TRNS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRNS,
			 KC_TRNS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_TRNS,
			 KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRNS, KC_TRNS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[_SYST] = LAYOUT(KC_TRNS, RESET, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
