#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(	KC_CAPS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, 
			KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, KC_BSLS, 
			LCTL_T(KC_ENT), LSFT_T(KC_A), LGUI_T(KC_R), LALT_T(KC_S), LCTL_T(KC_T), KC_G, KC_M, RCTL_T(KC_N), RALT_T(KC_E), RGUI_T(KC_I), RSFT_T(KC_O), RCTL_T(KC_ENT), 
			LSFT_T(KC_ESC), LCTL_T(KC_Z), KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_ESC), 
			MO(4), KC_NO, KC_NO, KC_NO, MO(4), LT(3, KC_BSPACE), LCTL_T(KC_DEL), LSFT_T(KC_ENT), LT(2, KC_SPACE), MO(4), KC_NO, KC_NO, KC_NO, MO(4)),
	[1] = LAYOUT(	KC_CAPS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, 
			KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, 
			LCTL_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, LCTL_T(KC_ENT), 
			KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, 
			MO(4), KC_NO, KC_LCTL, KC_LGUI, KC_LALT, LT(3, KC_BSPACE), LCTL_T(KC_DEL), LSFT_T(KC_BSPC), LT(2, KC_SPACE), KC_RALT, KC_RGUI, KC_RCTL, KC_NO, MO(4)),
	[2] = LAYOUT(	KC_TRNS, KC_NO, KC_NO, KC_LT, KC_GT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSLS, KC_TRNS, 
			KC_TRNS, KC_NO, KC_TILD, KC_LCBR, KC_RCBR, KC_UNDS, KC_COLN, KC_7, KC_8, KC_9, KC_PAST, KC_TRNS, 
			KC_TRNS, KC_NO, KC_GRV, KC_LPRN, KC_RPRN, KC_MINS, KC_SCLN, KC_4, KC_5, KC_6, KC_PMNS, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_EQL, KC_1, KC_2, KC_3, KC_PPLS, KC_TRNS, KC_TRNS, 
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_DOT, KC_NO, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(	KC_TRNS, KC_NO, KC_NO, KC_LT, KC_GT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSLS, KC_TRNS, 
			KC_TRNS, KC_NO, KC_TILD, KC_LCBR, KC_RCBR, KC_UNDS, KC_COLN, KC_AMPR, KC_ASTR, KC_NO, KC_PAST, KC_TRNS, 
			KC_TRNS, KC_NO, KC_GRV, KC_LPRN, KC_RPRN, KC_MINS, KC_SCLN, KC_DLR, KC_PERC, KC_CIRC, KC_PMNS, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_EQL, KC_EXLM, KC_AT, KC_HASH, KC_PPLS, KC_TRNS, 
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT(	KC_TRNS, TO(5), DF(0), DF(1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
			KC_TRNS, KC_NO, KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_INS, KC_HOME, KC_UP, KC_PGUP, KC_NO, KC_TRNS, 
			KC_TRNS, KC_LSFT, LGUI_T(KC_VOLD), LALT_T(KC_VOLU), LCTL_T(KC_MUTE), KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_END, KC_NO, KC_PGDN, KC_NO, KC_TRNS, KC_TRNS, 
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[5] = LAYOUT(	KC_TRNS, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
			KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};



